//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoobooWebMatrixExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KoobooWebMatrixExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .CreateQuery().
        /// </summary>
        internal static string ContentQuery_CreateQuery {
            get {
                return ResourceManager.GetString("ContentQuery_CreateQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentHelper.MediaFolder(folderName).
        /// </summary>
        internal static string ContentQuery_MediaFolder {
            get {
                return ResourceManager.GetString("ContentQuery_MediaFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .OrderBy(string field).
        /// </summary>
        internal static string ContentQuery_Order_OrderBy {
            get {
                return ResourceManager.GetString("ContentQuery_Order_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .OrderByDescending(string field).
        /// </summary>
        internal static string ContentQuery_Order_OrderByDescending {
            get {
                return ResourceManager.GetString("ContentQuery_Order_OrderByDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Categories(&quot;CategoryFolder&quot;).
        /// </summary>
        internal static string ContentQuery_Result_Categories {
            get {
                return ResourceManager.GetString("ContentQuery_Result_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Children(&quot;CommentsFolder&quot;).
        /// </summary>
        internal static string ContentQuery_Result_Children {
            get {
                return ResourceManager.GetString("ContentQuery_Result_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Count().
        /// </summary>
        internal static string ContentQuery_Result_Count {
            get {
                return ResourceManager.GetString("ContentQuery_Result_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .First().
        /// </summary>
        internal static string ContentQuery_Result_First {
            get {
                return ResourceManager.GetString("ContentQuery_Result_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .FirstOrDefault().
        /// </summary>
        internal static string ContentQuery_Result_FirstOrDefault {
            get {
                return ResourceManager.GetString("ContentQuery_Result_FirstOrDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Last().
        /// </summary>
        internal static string ContentQuery_Result_Last {
            get {
                return ResourceManager.GetString("ContentQuery_Result_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .LastOrDefault().
        /// </summary>
        internal static string ContentQuery_Result_LastOrDefault {
            get {
                return ResourceManager.GetString("ContentQuery_Result_LastOrDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Parent(&quot;ParentFolder&quot;).
        /// </summary>
        internal static string ContentQuery_Result_Parent {
            get {
                return ResourceManager.GetString("ContentQuery_Result_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentHelper.Schema(schemaName).
        /// </summary>
        internal static string ContentQuery_Schema {
            get {
                return ResourceManager.GetString("ContentQuery_Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Skip(int count).
        /// </summary>
        internal static string ContentQuery_Skip {
            get {
                return ResourceManager.GetString("ContentQuery_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Take(int count).
        /// </summary>
        internal static string ContentQuery_Take {
            get {
                return ResourceManager.GetString("ContentQuery_Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentHelper.TextFolder(folderName).
        /// </summary>
        internal static string ContentQuery_TextFolder {
            get {
                return ResourceManager.GetString("ContentQuery_TextFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .WhereBetween(string fieldName, object start, object end).
        /// </summary>
        internal static string ContentQuery_Where_WhereBetween {
            get {
                return ResourceManager.GetString("ContentQuery_Where_WhereBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .WhereBetweenOrEqual(string fieldName, object start, object end).
        /// </summary>
        internal static string ContentQuery_Where_WhereBetweenOrEqual {
            get {
                return ResourceManager.GetString("ContentQuery_Where_WhereBetweenOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .WhereCategory(ContentHelper.TextFolder(&quot;CategoryFolder&quot;).CreateQuery().WhereEquals(&quot;UUID&quot;, &quot;&quot;)).
        /// </summary>
        internal static string ContentQuery_Where_WhereCategory {
            get {
                return ResourceManager.GetString("ContentQuery_Where_WhereCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .WhereContains(string fieldName, object value).
        /// </summary>
        internal static string ContentQuery_Where_WhereContains {
            get {
                return ResourceManager.GetString("ContentQuery_Where_WhereContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .WhereEndsWith(string fieldName, object value).
        /// </summary>
        internal static string ContentQuery_Where_WhereEndsWith {
            get {
                return ResourceManager.GetString("ContentQuery_Where_WhereEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .WhereEquals(string fieldName, object value).
        /// </summary>
        internal static string ContentQuery_Where_WhereEquals {
            get {
                return ResourceManager.GetString("ContentQuery_Where_WhereEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .WhereGreaterThan(string fieldName, object value).
        /// </summary>
        internal static string ContentQuery_Where_WhereGreaterThan {
            get {
                return ResourceManager.GetString("ContentQuery_Where_WhereGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .WhereGreaterThanOrEqual(string fieldName, object value).
        /// </summary>
        internal static string ContentQuery_Where_WhereGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("ContentQuery_Where_WhereGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .WhereLessThan(string fieldName, object value).
        /// </summary>
        internal static string ContentQuery_Where_WhereLessThan {
            get {
                return ResourceManager.GetString("ContentQuery_Where_WhereLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .WhereLessThanOrEqual(string fieldName, object value).
        /// </summary>
        internal static string ContentQuery_Where_WhereLessThanOrEqual {
            get {
                return ResourceManager.GetString("ContentQuery_Where_WhereLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .WhereNotEquals(string fieldName, object value).
        /// </summary>
        internal static string ContentQuery_Where_WhereNotEquals {
            get {
                return ResourceManager.GetString("ContentQuery_Where_WhereNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .WhereStartsWith(string fieldName, object value).
        /// </summary>
        internal static string ContentQuery_Where_WhereStartsWith {
            get {
                return ResourceManager.GetString("ContentQuery_Where_WhereStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;common-form&quot;&gt;
        ///    &lt;h5 class=&quot;title&quot;&gt;Add content&lt;/h5&gt;
        ///    &lt;form method=&quot;post&quot; action=&quot;@Url.FrontUrl().SubmissionUrl(&quot;PostComment&quot;)&quot;&gt;
        ///        @Html.AntiForgeryToken()       
        ///        @*&lt;input type=&quot;hidden&quot; name=&quot;SuccessedUrl&quot; value=&apos;@Url.FrontUrl().PageUrl(&quot;Thankyou&quot;)&apos;/&gt;*@
        ///		@*&lt;input type=&quot;hidden&quot; name=&quot;FailedUrl&quot; value=&apos;@Url.FrontUrl().PageUrl(&quot;Failed&quot;)&apos;/&gt;*@
        ///        @*&lt;input type=&quot;hidden&quot; name=&quot;JsonResult&quot; value=&apos;true&apos;/&gt;*@
        ///        @*&lt;input type=&quot;hidden&quot; name=&quot;Categories[0].FolderName&quot; value [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form_AddContent {
            get {
                return ResourceManager.GetString("Form_AddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{ var guid = Guid.NewGuid(); }
        ///&lt;script type=&quot;text/javascript&quot; type=&quot;text/javascript&quot;&gt;
        ///    $(function(){
        ///        var form = $(&apos;#form-@guid&apos;).ajaxForm({
        ///            dataType: &apos;json&apos;,
        ///            type:&apos;post&apos;,
        ///            beforeSerialize: function ($form, options) {
        ///
        ///                //inform the server you need JsonResult return
        ///                var jsonResultHidden = form.find(&apos;input:hidden[name=JsonResult]&apos;).val(true);
        ///                if (!jsonResultHidden.length) {
        ///                    jsonResultHi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form_Ajax_AddContent {
            get {
                return ResourceManager.GetString("Form_Ajax_AddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{ var guid = Guid.NewGuid(); }
        ///&lt;script type=&quot;text/javascript&quot; type=&quot;text/javascript&quot;&gt;
        ///    $(function(){
        ///        var form = $(&apos;#form-@guid&apos;).ajaxForm({
        ///            dataType: &apos;json&apos;,
        ///            type:&apos;post&apos;,
        ///            beforeSerialize: function ($form, options) {
        ///
        ///                //inform the server you need JsonResult return
        ///                var jsonResultHidden = form.find(&apos;input:hidden[name=JsonResult]&apos;).val(true);
        ///                if (!jsonResultHidden.length) {
        ///                    jsonResultHi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form_Ajax_UpdateContent {
            get {
                return ResourceManager.GetString("Form_Ajax_UpdateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;common-form&quot;&gt;
        ///    &lt;h6 class=&quot;title&quot;&gt;Contact us&lt;/h6&gt;
        ///    &lt;form method=&quot;post&quot; action=&quot;@Url.FrontUrl().SubmissionUrl(&quot;ContactUs&quot;)&quot;&gt;
        ///        @Html.AntiForgeryToken()
        ///        &lt;!-- this contact form will send an email to the email address defined in system/settings/smtp--&gt;
        ///        @*&lt;input type=&quot;file&quot; name=&quot;image&quot;/&gt;*@
        ///        @*&lt;input type=&quot;hidden&quot; name=&quot;SuccessedUrl&quot; value=&apos;@Url.FrontUrl().PageUrl(&quot;Thankyou&quot;)&apos;/&gt;*@
        ///        @*&lt;input type=&quot;hidden&quot; name=&quot;FailedUrl&quot; value=&apos;@Url.FrontUrl().PageUrl(&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form_ContactUs {
            get {
                return ResourceManager.GetString("Form_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;common-form&quot;&gt;
        ///    &lt;form action=&quot;@Url.FrontUrl().SubmissionUrl(&quot;DeleteComment&quot;, new { uuid = comment.UUID })&quot; method=&quot;post&quot;&gt;
        ///        @Html.AntiForgeryToken()
        ///        &lt;input type=&quot;submit&quot; value=&quot;Delete&quot; /&gt;
        ///    &lt;/form&gt;    
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Form_DeleteContent {
            get {
                return ResourceManager.GetString("Form_DeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using Kooboo.CMS.Search;
        ///@using Kooboo.CMS.Content.Models;
        ///
        /// &lt;form action=&quot;@Url.FrontUrl().PageUrl(&quot;search&quot;)&quot; method=&quot;get&quot;&gt;     
        ///        &lt;input type=&quot;text&quot; name=&quot;key&quot; id=&quot;searchBox&quot; /&gt;
        ///        &lt;button type=&quot;submit&quot;&gt;
        ///            Search&lt;/button&gt;
        ///  &lt;/form&gt;
        ///
        ///@{
        ///    var key = Page_Context.Current.PageRequestContext.AllQueryString[&quot;key&quot;];
        ///    var strPageIndex = Page_Context.Current.PageRequestContext.AllQueryString[&quot;pageIndex&quot;];
        ///    var pageIndex =1;
        ///    if (!string.IsNullOrEmpty(strPageIndex))
        ///	{        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form_Search {
            get {
                return ResourceManager.GetString("Form_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;common-form&quot;&gt;
        ///    &lt;h5 class=&quot;title&quot;&gt;Update content&lt;/h5&gt;
        ///    &lt;form method=&quot;post&quot; action=&quot;@SubmissionHelper.UpdateContentUrl()&quot;&gt;
        ///        @Html.AntiForgeryToken()
        ///        &lt;input type=&quot;hidden&quot; name=&quot;FolderName&quot; value=&quot;@SecurityHelper.Encrypt(ViewBag.Article.FolderName)&quot; /&gt;
        ///        &lt;input type=&quot;hidden&quot; name=&quot;Published&quot; value=&quot;true&quot; /&gt;
        ///        &lt;input type=&quot;hidden&quot; name=&quot;uuid&quot; value=&quot;@ViewBag.Article.UUID&quot; /&gt;
        ///        @*&lt;input type=&quot;hidden&quot; name=&quot;SuccessedUrl&quot; value=&apos;@Url.FrontUrl().PageUrl(&quot;Than [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form_UpdateContent {
            get {
                return ResourceManager.GetString("Form_UpdateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ViewHelper.EditField(item, &quot;fieldName&quot;).
        /// </summary>
        internal static string InlineEdit_EditField {
            get {
                return ResourceManager.GetString("InlineEdit_EditField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ViewHelper.EditFieldAttributes(item, &quot;fieldName&quot;).
        /// </summary>
        internal static string InlineEdit_EditFieldAtributes {
            get {
                return ResourceManager.GetString("InlineEdit_EditFieldAtributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ViewHelper.EditItemAttributes(item).
        /// </summary>
        internal static string InlineEdit_EditItemAtributes {
            get {
                return ResourceManager.GetString("InlineEdit_EditItemAtributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @(&quot;Label Text&quot;.Label()).
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	@Html.FrontHtml().HtmlTitle()
        ///	@Html.FrontHtml().Meta()
        ///	@Html.FrontHtml().RegisterStyles()
        ///  	@Html.FrontHtml().RegisterScripts()
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div&gt;
        ///        @Html.FrontHtml().Position(&quot;Main&quot;)
        ///    &lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Layout_Default {
            get {
                return ResourceManager.GetString("Layout_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    @Html.FrontHtml().HtmlTitle()
        ///    @Html.FrontHtml().Meta()
        ///    &lt;!-- The styles below should be move into css files --&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        /* Layout:This should be put in layout.css */
        ///        #body-container {
        ///            margin: 0 auto;
        ///            width: 960px;
        ///        }
        ///        #header {
        ///            margin-bottom: 10px;
        ///        }
        ///        #main-container {
        ///            margin-bottom: 10px;
        ///        }
        ///        /* End layout */
        ///    &lt;/style&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Layout_OneColumn {
            get {
                return ResourceManager.GetString("Layout_OneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    @Html.FrontHtml().HtmlTitle()
        ///    @Html.FrontHtml().Meta()
        ///    &lt;!-- The styles below should be move into css files --&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        /* Layout:This should be put in layout.css */
        ///        #body-container {
        ///            margin: 0 auto;
        ///            width: 960px;
        ///        }
        ///        #header {
        ///            margin-bottom: 10px;
        ///        }
        ///        #main-container {
        ///            margin-bottom: 10px;
        ///        }
        ///        #left-sidebar {
        ///            fl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Layout_ThreeColumns {
            get {
                return ResourceManager.GetString("Layout_ThreeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    @Html.FrontHtml().HtmlTitle()
        ///    @Html.FrontHtml().Meta()
        ///    &lt;!-- The styles below should be move into css files --&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        /* Layout:This should be put in layout.css */
        ///        #body-container {
        ///            margin: 0 auto;
        ///            width: 960px;
        ///        }
        ///        #header {
        ///            margin-bottom: 10px;
        ///        }
        ///        #main-container {
        ///            margin-bottom: 10px;
        ///        }
        ///        #sidebar {
        ///            float:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Layout_TwoColumns {
            get {
                return ResourceManager.GetString("Layout_TwoColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Url.FrontUrl().FileUrl(&quot;Logo.png&quot;).
        /// </summary>
        internal static string Link_FileUrl {
            get {
                return ResourceManager.GetString("Link_FileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Url.FrontUrl().MediaContentUrl(fullFoldername, fileName).
        /// </summary>
        internal static string Link_MediaContentUrl {
            get {
                return ResourceManager.GetString("Link_MediaContentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.FrontHtml().PageLink(&quot;sample&quot;, &quot;Index&quot;).
        /// </summary>
        internal static string Link_PageLink {
            get {
                return ResourceManager.GetString("Link_PageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.FrontHtml().PageLink(&quot;Link Text&quot;, &quot;Index&quot;, new{ key=&quot;value&quot;}, new { title=&quot;title&quot;}).
        /// </summary>
        internal static string Link_PageLinkWithParams {
            get {
                return ResourceManager.GetString("Link_PageLinkWithParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Url.FrontUrl().PageUrl(&quot;Index&quot;).
        /// </summary>
        internal static string Link_PageUrl {
            get {
                return ResourceManager.GetString("Link_PageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Url.FrontUrl().PageUrl(&quot;Index&quot;, new { key = &quot;hello&quot;}).
        /// </summary>
        internal static string Link_PageUrlWithParams {
            get {
                return ResourceManager.GetString("Link_PageUrlWithParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.FrontHtml().ResizeImage(imagePath, width, height).
        /// </summary>
        internal static string Link_ResizeImage {
            get {
                return ResourceManager.GetString("Link_ResizeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Url.FrontUrl().ResizeImageUrl(imagePath, width, height).
        /// </summary>
        internal static string Link_ResizeImageUrl {
            get {
                return ResourceManager.GetString("Link_ResizeImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Url.FrontUrl().ScriptFileUrl(&quot;myscript.js&quot;).
        /// </summary>
        internal static string Link_ScriptFileUrl {
            get {
                return ResourceManager.GetString("Link_ScriptFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Url.FrontUrl().SubmissionUrl(&quot;SubmissionName&quot;).
        /// </summary>
        internal static string Link_SubmissionUrl {
            get {
                return ResourceManager.GetString("Link_SubmissionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Url.FrontUrl().ThemeFileUrl(&quot;images/header-bg.png&quot;).
        /// </summary>
        internal static string Link_ThemeFileUrl {
            get {
                return ResourceManager.GetString("Link_ThemeFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Url.FrontUrl().ViewUrl(&quot;Index&quot;, new { key = &quot;hello&quot;}).
        /// </summary>
        internal static string Link_ViewUrlWithParams {
            get {
                return ResourceManager.GetString("Link_ViewUrlWithParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;breadcrumb&quot;&gt;
        ///@foreach (var item in MenuHelper.Breadcrumb())
        ///{
        ///    &lt;li&gt;@Html.FrontHtml().PageLink(item.LinkText, item.FullName)&lt;/li&gt;
        ///    &lt;li class=&quot;separator&quot;&gt;|&lt;/li&gt;
        ///}
        ///&lt;li&gt;@(Page_Context.Current.ContentTitle??MenuHelper.Current().LinkText)&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        internal static string Menu_Breadcrumb {
            get {
                return ResourceManager.GetString("Menu_Breadcrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{var current = MenuHelper.Current();}.
        /// </summary>
        internal static string Menu_CurrentPage {
            get {
                return ResourceManager.GetString("Menu_CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{bool isCurrent =  MenuHelper.IsCurrent(page);}.
        /// </summary>
        internal static string Menu_CurrentPageChecker {
            get {
                return ResourceManager.GetString("Menu_CurrentPageChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{var parent = MenuHelper.Parent();}.
        /// </summary>
        internal static string Menu_ParentPage {
            get {
                return ResourceManager.GetString("Menu_ParentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;menu&quot;&gt;
        ///@foreach (var item in MenuHelper.Sibling())
        ///{
        ///    if (item.Navigation.Show)
        ///    {
        ///        &lt;li class =&apos;@(MenuHelper.IsCurrent(item) ? &quot;current&quot; : &quot;&quot;)&apos;&gt;@Html.FrontHtml().PageLink(item.LinkText, item.FullName)&lt;/li&gt;
        ///    }
        ///}&lt;/ul&gt;.
        /// </summary>
        internal static string Menu_SiblingPages {
            get {
                return ResourceManager.GetString("Menu_SiblingPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;menu&quot;&gt;
        ///@foreach (var item in MenuHelper.Sub())
        ///{
        ///    if (item.Navigation.Show)
        ///    {
        ///        &lt;li class =&apos;@(MenuHelper.IsCurrent(item) ? &quot;current&quot; : &quot;&quot;)&apos;&gt;@Html.FrontHtml().PageLink(item.LinkText, item.FullName)&lt;/li&gt;
        ///    }
        ///}&lt;/ul&gt;.
        /// </summary>
        internal static string Menu_SubPages {
            get {
                return ResourceManager.GetString("Menu_SubPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;menu&quot;&gt;
        ///@foreach (var item in MenuHelper.Top())
        ///{
        ///    if (item.Navigation.Show)
        ///    {
        ///       &lt;li class =&apos;@(MenuHelper.IsCurrent(item) ? &quot;current&quot; : &quot;&quot;)&apos;&gt; @Html.FrontHtml().PageLink(item.LinkText, item.FullName)&lt;/li&gt;
        ///    }
        ///}&lt;/ul&gt;.
        /// </summary>
        internal static string Menu_TopPages {
            get {
                return ResourceManager.GetString("Menu_TopPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @foreach(var file in ContentHelper.SplitMultiFiles(ViewBag.Article.Images))
        ///{
        ///	&lt;img src=&quot;@file&quot; alt=&quot;&quot;/&gt;
        ///}.
        /// </summary>
        internal static string MultiFilesField {
            get {
                return ResourceManager.GetString("MultiFilesField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.FrontHtml().Position(&quot;Main&quot;).
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Page_Context.Current.PageRequestContext.AllQueryString[&quot;id&quot;].
        /// </summary>
        internal static string QueryString {
            get {
                return ResourceManager.GetString("QueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.FrontHtml().Meta().
        /// </summary>
        internal static string RegisterMeta {
            get {
                return ResourceManager.GetString("RegisterMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.FrontHtml().RegisterScripts().
        /// </summary>
        internal static string RegisterScripts {
            get {
                return ResourceManager.GetString("RegisterScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.FrontHtml().RegisterStyles().
        /// </summary>
        internal static string RegisterStyles {
            get {
                return ResourceManager.GetString("RegisterStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.FrontHtml().HtmlTitle().
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.FrontHtml().RenderHtmlBlock(&quot;blockName&quot;).
        /// </summary>
        internal static string RenderHtmlBlock {
            get {
                return ResourceManager.GetString("RenderHtmlBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.FrontHtml().RenderView(&quot;MyView&quot;, ViewData).
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
